import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";

const studies: Record<string, { title: string; eyebrow: string; intro: string; problem: string; outcome: string; stack: string[]; lesson: string; image: string; imageAlt: string }> = {
  "dance-studio-costume-manager": { title:"Dance Studio Costume Manager", eyebrow:"Product design · Full-stack development", intro:"A web application for recording dancer measurements and matching them to vendor-specific costume sizes.", problem:"Costume ordering requires accurate measurements, vendor size charts, and repeated manual lookups. When records and reference materials are in different places, it takes longer to prepare an order and creates more room for mistakes.", outcome:"I built a tool that keeps measurements organized and converts them into the right vendor sizes. It makes the ordering process faster and gives the user one place to work from.", stack:["React", "Supabase", "Tailwind CSS"], lesson:"A useful side project does not need a large audience. It needs to solve a problem clearly enough that someone can use it without extra instructions.", image:"/images/DSCMPoster2.jpg", imageAlt:"Dance Studio Costume Manager showing dancer measurements and vendor costume sizes" },
  autofarm: { title:"AutoFarm", eyebrow:"Computer vision · Senior capstone", intro:"A senior capstone project that used plant images to identify health and growth-stage information.", problem:"The goal was to explore whether computer vision could help monitor maize plants. We needed to turn image-processing results into something a user could upload, review, and understand through a web application.", outcome:"I helped build the React and Flask workflow for uploading images and viewing results. The project included leaf count, color analysis, and growth-stage detection as a proof of concept.", stack:["React", "Flask", "Python"], lesson:"Building the model was only part of the project. I also learned that the interface matters because it determines whether someone can understand and use the result.", image:"/images/autoFarmPoster.png", imageAlt:"AutoFarm senior capstone research poster" },
  "attitudes-performing-arts": { title:"Attitudes Performing Arts", eyebrow:"Information architecture · Website redesign", intro:"A website redesign for a local performing arts studio.", problem:"Families needed to find class schedules, enrollment details, and contact information quickly. The existing site had the information, but it was difficult to scan and especially hard to use on a phone.", outcome:"I reorganized the site around the questions a new family is likely to have, improved the mobile experience, and made the next steps easier to find.", stack:["UX design", "Responsive UI", "Content strategy"], lesson:"A redesign is not just about making a site look newer. It should help visitors find the information they came for with less effort.", image:"/images/AttitudesPoster.jpg", imageAlt:"Attitudes Performing Arts website redesign homepage" },
};

export function generateStaticParams() { return Object.keys(studies).map((slug) => ({ slug })); }

export default async function ProjectPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const study = studies[slug]; if (!study) notFound();
  return <main className="shell editorial-page case-study"><Link className="back-link" href="/projects">← All projects</Link><p className="section-label">{study.eyebrow}</p><h1>{study.title}</h1><p className="lede">{study.intro}</p><div className="case-hero-art"><Image src={study.image} alt={study.imageAlt} width={1400} height={760} priority /></div><div className="case-meta"><div><p className="section-label">The problem</p><p>{study.problem}</p></div><div><p className="section-label">Built with</p><p>{study.stack.join(" · ")}</p></div></div><section><p className="section-label">What changed</p><h2>{study.outcome}</h2></section><aside className="lesson"><p className="section-label">What I learned</p><p>{study.lesson}</p></aside></main>;
}
